# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: node.js

on:
  push:
    branches: [ "main", "stage"]
  pull_request:
    branches: [ "main", "stage"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i
    - run: npm run build-production 

    - name: Deploy to Stage
        if: ${{ github.ref == 'refs/heads/stage' }}
        run: |
          mkdir -p stage
          cp -r backend/ stage/
          cd stage
          cp /env/.env.stage .env
          pm2 restart backend-stage 

    - name: Deploy to Production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          mkdir -p production
          cp -r backend/ production/
          cd production
          cp /env/.env.production .env
          pm2 restart backend-production
